name: ci

on:
  push:
    branches: master

env:
  IMAGE_NAME: go-http-logger

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set date and time var
        run: echo "NOW=$(date +%d%m%Y%H%M)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          push: true
          tags: | 
            skbki/${{ env.IMAGE_NAME }}:latest
            skbki/${{ env.IMAGE_NAME }}:$NOW
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:$NOW
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}